# Generated by Django 3.0.3 on 2020-02-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=50, verbose_name='ФИО')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Пароль')),
                ('status', models.BooleanField(blank=True, max_length=1, verbose_name='Уровень доступа')),
                ('active', models.BooleanField(blank=True, max_length=1, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['fio'],
            },
        ),
    ]
