# Generated by Django 3.0.3 on 2020-02-05 13:20

import client.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, upload_to=client.utilities.get_timestamp_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(blank=True, max_length=1, verbose_name='Сложная авторизация'),
        ),
    ]
