# Generated by Django 3.0.3 on 2020-02-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20200227_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='photo',
            field=models.CharField(blank=True, max_length=100, verbose_name='URL фото по которому входили'),
        ),
    ]
