# Generated by Django 3.0.3 on 2020-02-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_auto_20200205_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('crypth', models.CharField(blank=True, choices=[('0', 'Без шифрования'), ('1', 'Электронная подпись DSA'), ('2', 'Электронная подпись RSA'), ('3', 'Шифр AES'), ('4', 'Шифр TripleDES')], max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.Client', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-date_created'],
            },
        ),
    ]
