# Generated by Django 3.0.3 on 2020-02-06 20:50

from django.db import migrations, models
import document.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='file',
            field=models.FileField(blank=True, upload_to=document.utilities.get_timestamp_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='crypth',
            field=models.CharField(blank=True, choices=[('0', 'Без шифрования'), ('1', 'Электронная подпись DSA'), ('2', 'Электронная подпись RSA'), ('3', 'Шифр AES'), ('4', 'Шифр TripleDES')], max_length=1, verbose_name='Метод шифрования'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
