# Generated by Django 3.0.3 on 2020-02-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20200209_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='decrypth',
            field=models.BooleanField(blank=True, default=1, max_length=1, verbose_name='Расшифровать'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='crypth',
            field=models.CharField(choices=[('0', 'Без шифрования'), ('1', 'Электронная подпись DSA'), ('2', 'Электронная подпись RSA'), ('3', 'Шифр AES'), ('4', 'Шифр TripleDES')], default=0, max_length=1, verbose_name='Метод шифрования'),
        ),
    ]
