# Generated by Django 3.0.3 on 2020-02-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20200216_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='decrypth',
            field=models.BooleanField(blank=True, default=0, max_length=1, verbose_name='Расшифровать'),
        ),
    ]
