# Generated by Django 3.0.3 on 2020-02-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20200216_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='finish',
            field=models.BooleanField(blank=True, default=1, max_length=1, verbose_name='Закончил шифрование'),
        ),
    ]
