# Generated by Django 3.0.3 on 2020-02-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_doc_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='file_download',
            field=models.CharField(default='', max_length=100, verbose_name='Ссылка на скачаивание'),
        ),
    ]
