# Generated by Django 3.0.3 on 2020-02-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_doc_file_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='active',
            field=models.BooleanField(default=1, max_length=1, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='decrypth',
            field=models.BooleanField(default=0, max_length=1, verbose_name='Расшифровать'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='file_download',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка на скачивание'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='finish',
            field=models.BooleanField(default=1, max_length=1, verbose_name='Закончил шифрование'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
