# Generated by Django 3.0.3 on 2020-02-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_auto_20200216_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='crypth',
            field=models.CharField(choices=[('0', 'Без шифрования'), ('1', 'Шифр AES'), ('2', 'Шифр TripleDES')], default=0, max_length=1, verbose_name='Метод шифрования'),
        ),
    ]
