# Generated by Django 3.0.3 on 2020-02-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_auto_20200220_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='file_download',
        ),
    ]
