# Generated by Django 3.0.3 on 2020-02-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
    ]
