# Generated by Django 3.0.3 on 2020-02-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0003_adminer_key_crypth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminer',
            name='key_crypth',
        ),
    ]
